
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movie-app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployment/argocd
    repoURL: https://github.com/KerolosAyman308/movie-reservation-system.git
    targetRevision: "staging"
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true