apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: movie-backend
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: movies-rollout