apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  hostPath:
    path: /movie/db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In
            values:
              - db
  capacity:
    storage: 250Mi
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  