apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: movie-reservation
data:
  MYSQL_DATABASE: bW92aWVz
  MYSQL_PASSWORD: YmFja2VuZA==
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_USER: YmFja2VuZA==
